# Generated by Django 3.0.2 on 2020-01-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200116_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, upload_to='guestions/', verbose_name='Изображение'),
        ),
    ]
