# Generated by Django 3.0.2 on 2020-01-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200116_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='vop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions'),
        ),
    ]
