# Generated by Django 3.0.2 on 2020-01-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200119_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroups',
            name='can_drop',
            field=models.BooleanField(default=False, verbose_name='Можно удалить группу'),
        ),
    ]
