# Generated by Django 3.0.2 on 2020-01-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
