# Generated by Django 3.0.2 on 2020-01-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('questions', '0009_userprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='группа отдела'),
        ),
    ]
