# Generated by Django 3.0.2 on 2020-01-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20200130_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('group_user', models.CharField(max_length=50, verbose_name='Группа пользователя')),
                ('sessiya', models.CharField(max_length=150, verbose_name='Сессия пользователя')),
                ('not_ok_vop', models.IntegerField(verbose_name='Не правильный ответ')),
                ('ok_vop', models.IntegerField(verbose_name='Правильный ответ')),
            ],
        ),
        migrations.DeleteModel(
            name='UserGroups',
        ),
        migrations.DeleteModel(
            name='UserProfil',
        ),
    ]
