# Generated by Django 3.0.2 on 2020-02-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200131_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersanswers',
            old_name='sessiya',
            new_name='session_key',
        ),
    ]
