# Generated by Django 3.0.2 on 2020-02-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20200201_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersanswers',
            name='not_ok_otv',
            field=models.IntegerField(default=0, null=True, verbose_name='Не правильный ответ'),
        ),
        migrations.AddField(
            model_name='usersanswers',
            name='ok_otv',
            field=models.IntegerField(default=0, null=True, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='usersanswers',
            name='not_ok_vop',
            field=models.IntegerField(default=0, null=True, verbose_name='Не правильный вопрос'),
        ),
        migrations.AlterField(
            model_name='usersanswers',
            name='ok_vop',
            field=models.IntegerField(default=0, null=True, verbose_name='Правильный вопрос'),
        ),
    ]
