# Generated by Django 3.0.2 on 2020-02-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20200203_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersanswers',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
    ]
